#!/usr/bin/env python3
"""
claude-sleuth :: report generator
ICD 203-compliant analytical briefing and findings memo generation.
Jinja2 templates -> HTML -> optional PDF via WeasyPrint.

Usage:
    from scripts.report_generator import ReportGenerator
    rg = ReportGenerator()
    html = rg.generate_briefing(data)
    rg.to_pdf(html, "briefing.pdf")
"""

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

try:
    from jinja2 import Template, Environment
    HAS_JINJA = True
except ImportError:
    HAS_JINJA = False

try:
    from weasyprint import HTML
    HAS_WEASYPRINT = True
except ImportError:
    HAS_WEASYPRINT = False


# ICD 203 probability scale
ICD_203_SCALE = {
    "almost_no_chance": {"range": "<5%", "label": "Almost no chance"},
    "very_unlikely": {"range": "5-20%", "label": "Very unlikely"},
    "unlikely": {"range": "20-45%", "label": "Unlikely"},
    "roughly_even": {"range": "45-55%", "label": "Roughly even chance"},
    "likely": {"range": "55-80%", "label": "Likely"},
    "very_likely": {"range": "80-95%", "label": "Very likely"},
    "almost_certain": {"range": ">95%", "label": "Almost certain(ly)"},
}

BRIEFING_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <style>
        body { font-family: 'Georgia', serif; max-width: 800px; margin: 0 auto; padding: 40px; color: #1a1a1a; line-height: 1.6; }
        .header { border-bottom: 3px solid #1a1a1a; padding-bottom: 16px; margin-bottom: 24px; }
        .classification { font-size: 14px; font-weight: bold; text-transform: uppercase; color: #c0392b; letter-spacing: 2px; }
        .title { font-size: 24px; margin: 8px 0; }
        .meta { font-size: 12px; color: #666; }
        .bluf { background: #f8f9fa; border-left: 4px solid #2c3e50; padding: 16px; margin: 24px 0; }
        .bluf-label { font-weight: bold; font-size: 12px; text-transform: uppercase; letter-spacing: 1px; color: #2c3e50; }
        .section { margin: 24px 0; }
        .section h2 { font-size: 16px; text-transform: uppercase; letter-spacing: 1px; border-bottom: 1px solid #ddd; padding-bottom: 4px; }
        .fact { color: #1a1a1a; }
        .assumption { color: #e67e22; font-style: italic; }
        .judgement { color: #2980b9; }
        .confidence { display: inline-block; padding: 2px 8px; border-radius: 3px; font-size: 11px; font-weight: bold; }
        .confidence-high { background: #27ae60; color: white; }
        .confidence-moderate { background: #f39c12; color: white; }
        .confidence-low { background: #e74c3c; color: white; }
        .footer { border-top: 1px solid #ddd; margin-top: 40px; padding-top: 16px; font-size: 11px; color: #999; }
        table { width: 100%; border-collapse: collapse; margin: 16px 0; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; font-size: 13px; }
        th { background: #f8f9fa; font-weight: bold; }
    </style>
</head>
<body>
    <div class="header">
        <div class="classification">{{ classification | default('UNCLASSIFIED') }}</div>
        <h1 class="title">{{ title }}</h1>
        <div class="meta">
            Case Reference: {{ case_ref | default('N/A') }} |
            Date: {{ date }} |
            Analyst: {{ analyst | default('claude-sleuth') }}
        </div>
    </div>

    <div class="bluf">
        <div class="bluf-label">Bottom Line Up Front</div>
        <p>{{ bluf }}</p>
    </div>

    {% if facts %}
    <div class="section">
        <h2>Key Facts</h2>
        {% for fact in facts %}
        <p class="fact">{{ fact }}</p>
        {% endfor %}
    </div>
    {% endif %}

    {% if assumptions %}
    <div class="section">
        <h2>Key Assumptions</h2>
        {% for assumption in assumptions %}
        <p class="assumption">{{ assumption }}</p>
        {% endfor %}
    </div>
    {% endif %}

    {% if judgements %}
    <div class="section">
        <h2>Analytical Judgements</h2>
        {% for j in judgements %}
        <p class="judgement">
            <span class="confidence confidence-{{ j.confidence | default('moderate') }}">{{ j.confidence | default('MODERATE') | upper }}</span>
            {{ j.text }}
        </p>
        {% endfor %}
    </div>
    {% endif %}

    {% if intelligence_gaps %}
    <div class="section">
        <h2>Intelligence Gaps</h2>
        {% for gap in intelligence_gaps %}
        <p>{{ gap }}</p>
        {% endfor %}
    </div>
    {% endif %}

    {% if recommendations %}
    <div class="section">
        <h2>Recommendations</h2>
        {% for rec in recommendations %}
        <p>{{ rec }}</p>
        {% endfor %}
    </div>
    {% endif %}

    <div class="footer">
        Generated by claude-sleuth report generator | {{ date }} |
        ICD 203 compliant format | {{ classification | default('UNCLASSIFIED') }}
    </div>
</body>
</html>
"""

FINDINGS_MEMO_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Findings Memo: {{ case_ref }}</title>
    <style>
        body { font-family: 'Helvetica Neue', sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; color: #1a1a1a; line-height: 1.5; }
        .header { border-bottom: 2px solid #333; padding-bottom: 12px; }
        h1 { font-size: 20px; }
        .section { margin: 20px 0; }
        .section h2 { font-size: 14px; text-transform: uppercase; letter-spacing: 1px; color: #555; }
        .confirmed { border-left: 3px solid #27ae60; padding-left: 12px; margin: 8px 0; }
        .unverified { border-left: 3px solid #f39c12; padding-left: 12px; margin: 8px 0; }
        .limitation { border-left: 3px solid #e74c3c; padding-left: 12px; margin: 8px 0; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Findings Memo</h1>
        <p>Case: {{ case_ref }} | Date: {{ date }} | Analyst: {{ analyst | default('claude-sleuth') }}</p>
    </div>

    {% if confirmed_findings %}
    <div class="section">
        <h2>Confirmed Findings</h2>
        {% for f in confirmed_findings %}
        <div class="confirmed">{{ f }}</div>
        {% endfor %}
    </div>
    {% endif %}

    {% if unverified_leads %}
    <div class="section">
        <h2>Unverified Leads</h2>
        {% for l in unverified_leads %}
        <div class="unverified">{{ l }}</div>
        {% endfor %}
    </div>
    {% endif %}

    {% if limitations %}
    <div class="section">
        <h2>Scope Limitations</h2>
        {% for lim in limitations %}
        <div class="limitation">{{ lim }}</div>
        {% endfor %}
    </div>
    {% endif %}
</body>
</html>
"""


class ReportGenerator:
    """ICD 203-compliant report generator."""

    def __init__(self):
        if not HAS_JINJA:
            raise ImportError("jinja2 is required: pip install jinja2")

    def generate_briefing(self, data: dict) -> str:
        """Generate analytical briefing HTML."""
        data.setdefault("date", datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"))
        template = Template(BRIEFING_TEMPLATE)
        return template.render(**data)

    def generate_findings_memo(self, data: dict) -> str:
        """Generate findings memo HTML."""
        data.setdefault("date", datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"))
        template = Template(FINDINGS_MEMO_TEMPLATE)
        return template.render(**data)

    def to_html(self, html: str, filepath: str) -> str:
        """Save HTML to file."""
        Path(filepath).write_text(html)
        return filepath

    def to_pdf(self, html: str, filepath: str) -> Optional[str]:
        """Convert HTML to PDF via WeasyPrint."""
        if not HAS_WEASYPRINT:
            return None
        HTML(string=html).write_pdf(filepath)
        return filepath

    @staticmethod
    def icd_203_scale() -> dict:
        return ICD_203_SCALE


def main():
    import argparse
    parser = argparse.ArgumentParser(description="Report generator")
    parser.add_argument("input", help="JSON data file for report")
    parser.add_argument("--type", choices=["briefing", "findings"], default="briefing", help="Report type")
    parser.add_argument("--html", help="Output HTML file")
    parser.add_argument("--pdf", help="Output PDF file")
    args = parser.parse_args()

    data = json.loads(Path(args.input).read_text())
    rg = ReportGenerator()

    if args.type == "briefing":
        html = rg.generate_briefing(data)
    else:
        html = rg.generate_findings_memo(data)

    if args.html:
        rg.to_html(html, args.html)
        print(f"HTML written to {args.html}")

    if args.pdf:
        result = rg.to_pdf(html, args.pdf)
        if result:
            print(f"PDF written to {args.pdf}")
        else:
            print("PDF generation requires weasyprint. Falling back to HTML only.")
            if not args.html:
                fallback = args.pdf.replace(".pdf", ".html")
                rg.to_html(html, fallback)
                print(f"HTML written to {fallback}")


if __name__ == "__main__":
    main()
